title: Bruno Santos
description: > # this means to ignore newlines until "baseurl:"
  Consultor independente TOTVS especialista em desenvolvimento ADVPL e WEB, 
  há mais de dez anos construindo soluções.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bruno Santos # add your name
author-img: bruno-santos.jpg # add your photo
about-author: Consultor independente TOTVS especialista em desenvolvimento ADVPL e WEB, há mais de dez anos construindo soluções. # add description
social-twitter: brunosps00 # add your Twitter handle
social-facebook: brunosps # add your Facebook handle
social-github: brunosps00 # add your Github handle
social-linkedin: brunosps # add your Linkedin handle
social-email: brunosps00@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: UA-115301730-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
